### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-css-frameworks-p1twXJ#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://GriffinMartin.github.io/MI-449-SS17-740-css-frameworks-p1twXJ/) and meets the following criteria:

- [x] Include the CSS and JS for Bootstrap 3 (not 4) in the page (including the "jQuery" dependency)
- [x] Use the `container` class to center your page content
- [x] Use a `navbar` class to display the name of your site and a list of at least 3 links (to past projects, or anything else) at the top of your page
- [x] Split your main content into 2 columns on large (`lg`) and medium (`md`) sized screens, but collapse them on top of each other on small (`sm`) and extra small (`xs`) screens
- [x] Use a `thumbnail` class on an at least one image in your page

Used Foundation 6 instead of Bootstrap.

**Comment by chrisvfritz** [comment]
Very nice! Definitely the best project I've seen today. 🚀 🥇 🎈 😄  Some things I like in particular:

- _Excellent_ file organization.
- Very well organized HTML. You've made it very easy for other developers to read!
- Many aspects have gone above and beyond, including:
  - Font Awesome icons
  - Custom CSS and JS
  - Reaching out to see if you could learn something new 🎉  🎉  🎉 

I only see a few areas for improvement:

### Headings should not be used to just make things bigger

I see you've used [an `h4`](https://github.com/GriffinMartin/MI-449-SS17-740-css-frameworks-p1twXJ/blob/master/index.html#L59-L60) element for some long-form content. Since this content is not _semantically_ a heading, I would change it to a `p` element instead, then add a `class` you can use to add styles in your `app.css` to make it bigger (e.g. with `font-size`).

### It's [a tab character](https://github.com/GriffinMartin/MI-449-SS17-740-css-frameworks-p1twXJ/blob/master/css/app.css#L2) 😬

You know what to do.

!["Take care of" the tab](https://cdn.meme.am/cache/instances/folder128/500x/74771128.jpg)

And remember, you can set up Atom to "Show Invisibles" (see the previous lesson) so that catching those tabs is easier!

### Unused `app.js` file

It looks like you've created an `app.js` where you're initializing Foundation's JS. This is great! However, you use the same code to initialize it manually in the `index.html` file. I'd delete the contents of that  `script` tag and link it to your `app.js` JS file instead.

### Another __optional__ enhancement

This part is _totally_ optional as you've already done a lot of work here, but on projects like this, I often find a round of iteration helpful for learning - especially because it always happens on real jobs. So imagine I'm the (non-technical) client and I come back to you with this request:

> We want the left-side of the menu to line up with the left side of the content. Right now, the menu is all the way to the left on large screens, instead of centered like the main content.

---

Let me know if you have any other questions or when it's ready for another look. Again, _great_ work here! 👍

**Comment by GriffinMartin** [comment]
@chrisvfritz Thanks for the awesome feedback! I made the recommended changes. :sparkles:

**Comment by chrisvfritz** [comment]
Very nice! 🎉 :shipit:
